### ISSUE TITLE
Unexpected size of k

### ISSUE THREAD

**Issue by stefanerb89** [schneebergerlab/findGSE#4]
Hello I got this message:

Error in findGSE(histo = args[1], sizek = args[2], outdir = args[3], exp_hom = strtoi(args[4])) : 
  Unexpected size of k: 100. Size k>=15 required. Program exited.
Execution halted

The code is

```
targetsizek     <- sizek
  if(targetsizek  < 15)
  {
    stop(paste("Unexpected size of k: ", targetsizek, ". Size k>=15 required. Program exited.\n",sep=""))
  }
```

Why I got this error when i choose a size of 100 ?

**Comment by HeQSun** [comment]
Hi, sorry for the late reply. But have you fixed the problem? It should not exit with larger k's. Did you try other values (while a proper k value can be 17-35 for short reads)?

Best,
Hequan
