### ISSUE TITLE
Can findGSE use third generation sequencing reads？

### ISSUE THREAD

**Issue by CSU-KangHu** [schneebergerlab/findGSE#7]
I'm using three generations of sequencing reads, and I want to estimate the coverage of the reads (no reference or assembly). Can findGSE use the third-generation sequencing reads and estimate the coverage of the reads?

**Comment by HeQSun** [comment]
Hi, 

Which type of third generation data did you mean? 

With nanopore reads, I am not sure because of the high sequencing errors.

If HiFi, I think it's possible to count k-mers, then you can estimate sequencing depth. 

Best,
Hequan
